### ISSUE TITLE
No longer on the store

### ISSUE THREAD

**Issue by Riley869** [devAdityaa/medium-breaker#1]
Medium breaker has been removed from the Chrome Web Store.

**Comment by apurva010** [comment]
+1

**Comment by devAdityaa** [comment]
Hello All, Medium Breaker is pulled down from the store after it hit 5K installs with 4.8 stars. But you can still use this by downloading this repository, and loading the extension as unpacked and then using it.
It still works.

**Comment by ScalarJerk** [comment]
@devAdityaa can you please add the installation and how to use the repo/extension documentation in the readme 🙏
